version: '3'
services:
  database:
    container_name: "sheets_database"
    image: "postgres"
    expose:
      - 5432
    ports:
      - 5432:5432
    env_file:
      - database.env
    volumes:
      - database-data:/var/lib/postgresql/sheets-data/
    restart: "always"

volumes:
  database-data:
